Added DBSCANFastRescan
gnn-tracking/gnn_tracking pull request #358
Opened 2023-07-14 22:26 UTC by jnpark3

Implemented DBSCANFastRescan, a class that helps with accelerating DBSCAN hyperparameter search.

2023-07-14 22:28 UTC, jnpark3 commented
pre-commit.ci autofix

2023-07-18 16:02 UTC, klieret requested changes

2023-07-18 16:02 UTC, klieret commented on src/gnn_tracking/postprocessing/fastrescanner.py
> +        neighborhoods = np.empty(len(n), dtype=object)
Just do `neighborhoods = np.array(np.split(filtered_edges[:,1], idx), dtype="object")`

2023-07-18 16:02 UTC, klieret commented on src/gnn_tracking/postprocessing/fastrescanner.py
> +        self.distances = np.concatenate(distances)
all attributes should be declared in `__init__`. Also mark as private (start with `_`)

2023-07-18 16:02 UTC, klieret commented on src/gnn_tracking/postprocessing/fastrescanner.py
> +        self.max_eps = max_eps
mark as private

2023-07-18 16:02 UTC, klieret commented on src/gnn_tracking/postprocessing/fastrescanner.py
> +    def __init__(self, X, max_eps=1, n_jobs=None):
put `, *, ` before `n_jobs`

2023-07-18 16:02 UTC, klieret commented
Btw, press `a` to hide all the annotations by codecov (I've disabled them but that's only gonna affect the next PR)

2023-07-18 22:10 UTC, klieret requested changes

2023-07-18 22:10 UTC, klieret commented on src/gnn_tracking/postprocessing/fastrescanner.py
> +    def __init__(self, X, max_eps=1, n_jobs=None):
`X` should be lower case

2023-07-18 22:16 UTC, klieret commented
Please also add [type hints](https://www.pythontutorial.net/python-basics/python-type-hints/)

Also make sure that you have pre-commit installed locally, the autofix didn't seem to work. 

```
pre-commit install
pre-commit run --all
```

2023-07-26 10:27 UTC, jnpark3 commented
Only change not added was the implementation of neighborhoods = np.array(np.split(filtered_edges[:,1], idx), dtype="object"), as for some reason tests on a notebook showed that this generated a different list of neighborhoods compared to the original implementation

2023-07-26 10:27 UTC, jnpark3 commented
Only change not added was the implementation of `neighborhoods = np.array(np.split(filtered_edges[:,1], idx), dtype="object")`, as for some reason tests on a notebook showed that this generated a different list of neighborhoods compared to the original implementation

2023-07-27 13:57 UTC, klieret commented
Closing this in favor of #378 (which is the same but pushed to a branch)

2023-07-27 13:57 UTC, closed without merging